# Generated by Django 2.1.3 on 2018-11-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Тип набою')),
            ],
            options={
                'verbose_name': 'Тип набою',
                'verbose_name_plural': 'Типи набоїв',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('second_name', models.CharField(max_length=30, verbose_name='По батькові')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('mobile', models.CharField(max_length=13, verbose_name='Номер мобільного')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/час зпису')),
            ],
            options={
                'verbose_name': 'Особа - реєстраційні данні',
                'verbose_name_plural': 'Особа - реєстраційні данні',
            },
        ),
        migrations.CreateModel(
            name='Shooting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Shooting', models.DateTimeField(auto_now_add=True, verbose_name='дата/час')),
                ('document', models.CharField(default='', max_length=20, verbose_name='Номер документа про оплату')),
                ('safe_number', models.CharField(default='', max_length=5, verbose_name='Номер сейфу зберігання')),
                ('ammo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ammo', verbose_name='Тип набоїв')),
            ],
            options={
                'verbose_name': 'Відстріл - запис відстрілу зброї',
                'verbose_name_plural': 'Відстріл - записи відстрілу зброї',
            },
        ),
        migrations.CreateModel(
            name='Wepon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=30, verbose_name='Марка')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('calibre', models.CharField(max_length=15, verbose_name='Калібр')),
                ('serial_number', models.CharField(max_length=30, verbose_name='Номер')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/час зпису')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person', verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Зброя',
                'verbose_name_plural': 'Зброя - перелік',
            },
        ),
        migrations.CreateModel(
            name='WeponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Тип зброї')),
                ('description_plural', models.CharField(default='asd', max_length=30, verbose_name='Тип зброї (множина)')),
            ],
            options={
                'verbose_name': 'Тип зброї',
                'verbose_name_plural': 'Типи зброї',
            },
        ),
        migrations.AddField(
            model_name='shooting',
            name='wepon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Wepon', verbose_name='Зброя'),
        ),
    ]
