# Generated by Django 2.1.3 on 2018-11-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Тип набою')),
            ],
            options={
                'verbose_name': 'Тип набою',
                'verbose_name_plural': 'Типи набоїв',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('second_name', models.CharField(max_length=30, verbose_name='По батькові')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('mobile', models.CharField(max_length=13, verbose_name='Номер мобільного')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/час зпису')),
            ],
            options={
                'verbose_name': 'Реєстраційні данні особи',
                'verbose_name_plural': 'Реєстраційні данні особи',
            },
        ),
        migrations.CreateModel(
            name='Shooting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Shooting', models.DateTimeField(auto_now_add=True, verbose_name='дата/час')),
                ('document', models.CharField(default='', max_length=20, verbose_name='Номер документа про оплату')),
                ('safe_number', models.CharField(default='', max_length=5, verbose_name='Номер сейфу зберігання')),
                ('ammo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Ammo', verbose_name='Тип набоїв')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Person', verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Запис відстрілу зброї',
                'verbose_name_plural': 'Записи відстрілу зброї',
            },
        ),
    ]
